### ISSUE TITLE
Error in the WSDL -> OWL transformation

### ISSUE THREAD

**Issue by cezarcp** [FORMAS/OWL-S-Composer#1]
After creating a web service and initialing the server for the first time, at the step that carries out the WSDL -> OWL transformation, an error with no message occurs.

![screen shot 2013-08-03 at 8 45 29 pm](https://f.cloud.github.com/assets/2272207/906373/7582727c-fc97-11e2-998a-26dbf19966ef.png)

In order to proceed, the user has to restart the server and go through the process again.

This problem was verified while following [this tutorial](http://homes.dcc.ufba.br/~dclaro/download/mate15/OWL-S%20Composer.pdf) in the step described in page 15.

**Comment by efraimmachado** [comment]
Cezar, 

This error was fixed. The fix will be add to avaliable code in this weekend. Anyway you can try to execute this action again following these tips:
1 - This error happens if the server is not running (did you check for errors while start the server?)
2 - Sometimes, Eclipse's ID not set correctly the selected file.

Then try to execute this action:
1 - make sure the server is ok
2 - selecting the file wsdl (mouse click). (not showed it your screenshot. Is the project Temperatura selected?)

**Comment by cezarcp** [comment]
The Temperatura project was selected and the server was running. I managed to proceed by restarting the server. I also repeated the whole process with a new project to check whether the error would happen again and it did. Restarting the server solved it again.
Anyway, glad to know it has already been fixed.
